#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 39
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 2
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 11

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  sym_variable = 3,
  sym_atom = 4,
  anon_sym_SQUOTE = 5,
  anon_sym_DQUOTE = 6,
  sym_escape_sequence = 7,
  sym_quoted_content = 8,
  anon_sym_LT_LT = 9,
  anon_sym_GT_GT = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_POUND_LBRACE = 15,
  anon_sym_POUND = 16,
  anon_sym_EQ = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_PIPE = 22,
  anon_sym_EQ_GT = 23,
  anon_sym_COLON_EQ = 24,
  anon_sym_COLON = 25,
  anon_sym_PLUS_PLUS = 26,
  anon_sym_DASH_DASH = 27,
  anon_sym_COMMA = 28,
  anon_sym_DOLLAR = 29,
  aux_sym_character_token1 = 30,
  aux_sym_integer_token1 = 31,
  aux_sym_integer_token2 = 32,
  sym_float = 33,
  aux_sym_comment_token1 = 34,
  aux_sym_comment_token2 = 35,
  sym_source = 36,
  sym__expression = 37,
  sym__identifier = 38,
  sym__atom = 39,
  sym_quoted_atom = 40,
  sym_string = 41,
  sym_bitstring = 42,
  sym_tuple = 43,
  sym_list = 44,
  sym_map = 45,
  sym_record = 46,
  sym_binary_operator = 47,
  sym__items = 48,
  sym_character = 49,
  sym_integer = 50,
  sym_comment = 51,
  aux_sym_source_repeat1 = 52,
  aux_sym_string_repeat1 = 53,
  aux_sym__items_repeat1 = 54,
  alias_sym_map_content = 55,
  alias_sym_record_content = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_variable] = "variable",
  [sym_atom] = "atom",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [sym_quoted_content] = "quoted_content",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_POUND] = "#",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PIPE] = "|",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_COLON] = ":",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_character_token1] = "character_token1",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [sym_float] = "float",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_source] = "source",
  [sym__expression] = "_expression",
  [sym__identifier] = "_identifier",
  [sym__atom] = "_atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym_string] = "string",
  [sym_bitstring] = "bitstring",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_map] = "map",
  [sym_record] = "record",
  [sym_binary_operator] = "binary_operator",
  [sym__items] = "_items",
  [sym_character] = "character",
  [sym_integer] = "integer",
  [sym_comment] = "comment",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym__items_repeat1] = "_items_repeat1",
  [alias_sym_map_content] = "map_content",
  [alias_sym_record_content] = "record_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_variable] = sym_variable,
  [sym_atom] = sym_atom,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_quoted_content] = sym_quoted_content,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_character_token1] = aux_sym_character_token1,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [sym_float] = sym_float,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_source] = sym_source,
  [sym__expression] = sym__expression,
  [sym__identifier] = sym__identifier,
  [sym__atom] = sym__atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym_string] = sym_string,
  [sym_bitstring] = sym_bitstring,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_map] = sym_map,
  [sym_record] = sym_record,
  [sym_binary_operator] = sym_binary_operator,
  [sym__items] = sym__items,
  [sym_character] = sym_character,
  [sym_integer] = sym_integer,
  [sym_comment] = sym_comment,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym__items_repeat1] = aux_sym__items_repeat1,
  [alias_sym_map_content] = alias_sym_map_content,
  [alias_sym_record_content] = alias_sym_record_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bitstring] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__items] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__items_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_map_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_record_content] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_comment_content = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
  field_quoted_end = 5,
  field_quoted_start = 6,
  field_right = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_comment_content] = "comment_content",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_quoted_end] = "quoted_end",
  [field_quoted_start] = "quoted_start",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 3},
  [9] = {.index = 3, .length = 1},
  [10] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_comment_content, 1},
  [1] =
    {field_quoted_end, 1},
    {field_quoted_start, 0},
  [3] =
    {field_name, 1},
  [4] =
    {field_name, 2},
  [5] =
    {field_quoted_end, 2},
    {field_quoted_start, 0},
  [7] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [6] = {
    [1] = alias_sym_map_content,
  },
  [8] = {
    [2] = alias_sym_map_content,
  },
  [9] = {
    [3] = alias_sym_record_content,
  },
  [10] = {
    [4] = alias_sym_record_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__items, 3,
    sym__items,
    alias_sym_map_content,
    alias_sym_record_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 41,
  [42] = 42,
  [43] = 38,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '$') ADVANCE(52);
      if (lookahead == '%') ADVANCE(63);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '+') ADVANCE(41);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == ':') ADVANCE(48);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(6);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(37);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead == '}') ADVANCE(35);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(54);
      if (lookahead == '%') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1)
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '^') ADVANCE(12);
      if (lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(25);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'f') ||
          lookahead == 'n' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(61);
      END_STATE();
    case 12:
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_atom);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_quoted_content);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_quoted_content);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_quoted_content);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_quoted_content);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_quoted_content);
      if (lookahead == '^') ADVANCE(12);
      if (lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(25);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'f') ||
          lookahead == 'n' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_quoted_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '{') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(49);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(50);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_character_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_character_token1);
      if (lookahead == ' ') ADVANCE(54);
      if (lookahead == '%') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_character_token1);
      if (lookahead == '%') ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_character_token1);
      if (lookahead == '^') ADVANCE(12);
      if (lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(25);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'f') ||
          lookahead == 'n' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '_') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'e') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '%') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '%') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '%') ADVANCE(64);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 65},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [aux_sym_integer_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [1] = {
    [sym_source] = STATE(59),
    [sym__expression] = STATE(37),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(1),
    [aux_sym_source_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(33),
    [sym_variable] = ACTIONS(33),
    [sym_atom] = ACTIONS(33),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_LT_LT] = ACTIONS(33),
    [anon_sym_GT_GT] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_POUND_LBRACE] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_EQ_GT] = ACTIONS(33),
    [anon_sym_COLON_EQ] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(35),
    [anon_sym_PLUS_PLUS] = ACTIONS(33),
    [anon_sym_DASH_DASH] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_DOLLAR] = ACTIONS(33),
    [aux_sym_integer_token1] = ACTIONS(35),
    [aux_sym_integer_token2] = ACTIONS(33),
    [sym_float] = ACTIONS(33),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(37),
    [anon_sym_RPAREN] = ACTIONS(37),
    [sym_variable] = ACTIONS(37),
    [sym_atom] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_LT_LT] = ACTIONS(37),
    [anon_sym_GT_GT] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_POUND_LBRACE] = ACTIONS(37),
    [anon_sym_POUND] = ACTIONS(39),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_PIPE] = ACTIONS(37),
    [anon_sym_EQ_GT] = ACTIONS(37),
    [anon_sym_COLON_EQ] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(39),
    [anon_sym_PLUS_PLUS] = ACTIONS(37),
    [anon_sym_DASH_DASH] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(37),
    [anon_sym_DOLLAR] = ACTIONS(37),
    [aux_sym_integer_token1] = ACTIONS(39),
    [aux_sym_integer_token2] = ACTIONS(37),
    [sym_float] = ACTIONS(37),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(41),
    [sym_variable] = ACTIONS(41),
    [sym_atom] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_LT_LT] = ACTIONS(41),
    [anon_sym_GT_GT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_POUND_LBRACE] = ACTIONS(41),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_COLON_EQ] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PLUS_PLUS] = ACTIONS(41),
    [anon_sym_DASH_DASH] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(41),
    [anon_sym_DOLLAR] = ACTIONS(41),
    [aux_sym_integer_token1] = ACTIONS(43),
    [aux_sym_integer_token2] = ACTIONS(41),
    [sym_float] = ACTIONS(41),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [sym_variable] = ACTIONS(45),
    [sym_atom] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [anon_sym_LT_LT] = ACTIONS(45),
    [anon_sym_GT_GT] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_POUND] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_EQ_GT] = ACTIONS(45),
    [anon_sym_COLON_EQ] = ACTIONS(45),
    [anon_sym_COLON] = ACTIONS(47),
    [anon_sym_PLUS_PLUS] = ACTIONS(45),
    [anon_sym_DASH_DASH] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_DOLLAR] = ACTIONS(45),
    [aux_sym_integer_token1] = ACTIONS(47),
    [aux_sym_integer_token2] = ACTIONS(45),
    [sym_float] = ACTIONS(45),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [6] = {
    [sym_comment] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [sym_variable] = ACTIONS(49),
    [sym_atom] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_LT_LT] = ACTIONS(49),
    [anon_sym_GT_GT] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_POUND_LBRACE] = ACTIONS(49),
    [anon_sym_POUND] = ACTIONS(51),
    [anon_sym_EQ] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym_PIPE] = ACTIONS(49),
    [anon_sym_EQ_GT] = ACTIONS(49),
    [anon_sym_COLON_EQ] = ACTIONS(49),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(49),
    [anon_sym_DASH_DASH] = ACTIONS(49),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_DOLLAR] = ACTIONS(49),
    [aux_sym_integer_token1] = ACTIONS(51),
    [aux_sym_integer_token2] = ACTIONS(49),
    [sym_float] = ACTIONS(49),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [sym_variable] = ACTIONS(53),
    [sym_atom] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_GT_GT] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(53),
    [anon_sym_POUND_LBRACE] = ACTIONS(53),
    [anon_sym_POUND] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(53),
    [anon_sym_PIPE] = ACTIONS(53),
    [anon_sym_EQ_GT] = ACTIONS(53),
    [anon_sym_COLON_EQ] = ACTIONS(53),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_DASH_DASH] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(53),
    [anon_sym_DOLLAR] = ACTIONS(53),
    [aux_sym_integer_token1] = ACTIONS(55),
    [aux_sym_integer_token2] = ACTIONS(53),
    [sym_float] = ACTIONS(53),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [8] = {
    [sym_comment] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_variable] = ACTIONS(57),
    [sym_atom] = ACTIONS(57),
    [anon_sym_SQUOTE] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_LT_LT] = ACTIONS(57),
    [anon_sym_GT_GT] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_POUND_LBRACE] = ACTIONS(57),
    [anon_sym_POUND] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_PIPE] = ACTIONS(57),
    [anon_sym_EQ_GT] = ACTIONS(57),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_PLUS_PLUS] = ACTIONS(57),
    [anon_sym_DASH_DASH] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_DOLLAR] = ACTIONS(57),
    [aux_sym_integer_token1] = ACTIONS(59),
    [aux_sym_integer_token2] = ACTIONS(57),
    [sym_float] = ACTIONS(57),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [9] = {
    [sym_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_variable] = ACTIONS(61),
    [sym_atom] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_LT_LT] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(61),
    [anon_sym_POUND_LBRACE] = ACTIONS(61),
    [anon_sym_POUND] = ACTIONS(65),
    [anon_sym_EQ] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_PIPE] = ACTIONS(61),
    [anon_sym_EQ_GT] = ACTIONS(61),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_COLON] = ACTIONS(65),
    [anon_sym_PLUS_PLUS] = ACTIONS(61),
    [anon_sym_DASH_DASH] = ACTIONS(61),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_DOLLAR] = ACTIONS(61),
    [aux_sym_integer_token1] = ACTIONS(65),
    [aux_sym_integer_token2] = ACTIONS(61),
    [sym_float] = ACTIONS(61),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [10] = {
    [sym_comment] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
    [sym_variable] = ACTIONS(67),
    [sym_atom] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_LT_LT] = ACTIONS(67),
    [anon_sym_GT_GT] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(67),
    [anon_sym_POUND_LBRACE] = ACTIONS(67),
    [anon_sym_POUND] = ACTIONS(69),
    [anon_sym_EQ] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_EQ_GT] = ACTIONS(67),
    [anon_sym_COLON_EQ] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(69),
    [anon_sym_PLUS_PLUS] = ACTIONS(67),
    [anon_sym_DASH_DASH] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(67),
    [anon_sym_DOLLAR] = ACTIONS(67),
    [aux_sym_integer_token1] = ACTIONS(69),
    [aux_sym_integer_token2] = ACTIONS(67),
    [sym_float] = ACTIONS(67),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [11] = {
    [sym_comment] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
    [sym_variable] = ACTIONS(71),
    [sym_atom] = ACTIONS(71),
    [anon_sym_SQUOTE] = ACTIONS(71),
    [anon_sym_DQUOTE] = ACTIONS(71),
    [anon_sym_LT_LT] = ACTIONS(71),
    [anon_sym_GT_GT] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(71),
    [anon_sym_RBRACK] = ACTIONS(71),
    [anon_sym_POUND_LBRACE] = ACTIONS(71),
    [anon_sym_POUND] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [anon_sym_EQ_GT] = ACTIONS(71),
    [anon_sym_COLON_EQ] = ACTIONS(71),
    [anon_sym_COLON] = ACTIONS(73),
    [anon_sym_PLUS_PLUS] = ACTIONS(71),
    [anon_sym_DASH_DASH] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(71),
    [anon_sym_DOLLAR] = ACTIONS(71),
    [aux_sym_integer_token1] = ACTIONS(73),
    [aux_sym_integer_token2] = ACTIONS(71),
    [sym_float] = ACTIONS(71),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [12] = {
    [sym_comment] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [sym_variable] = ACTIONS(75),
    [sym_atom] = ACTIONS(75),
    [anon_sym_SQUOTE] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(75),
    [anon_sym_LT_LT] = ACTIONS(75),
    [anon_sym_GT_GT] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(75),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_POUND_LBRACE] = ACTIONS(75),
    [anon_sym_POUND] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(75),
    [anon_sym_EQ_GT] = ACTIONS(75),
    [anon_sym_COLON_EQ] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_PLUS_PLUS] = ACTIONS(75),
    [anon_sym_DASH_DASH] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_DOLLAR] = ACTIONS(75),
    [aux_sym_integer_token1] = ACTIONS(77),
    [aux_sym_integer_token2] = ACTIONS(75),
    [sym_float] = ACTIONS(75),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [sym_variable] = ACTIONS(79),
    [sym_atom] = ACTIONS(79),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [anon_sym_DQUOTE] = ACTIONS(79),
    [anon_sym_LT_LT] = ACTIONS(79),
    [anon_sym_GT_GT] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(79),
    [anon_sym_RBRACK] = ACTIONS(79),
    [anon_sym_POUND_LBRACE] = ACTIONS(79),
    [anon_sym_POUND] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_PIPE] = ACTIONS(79),
    [anon_sym_EQ_GT] = ACTIONS(79),
    [anon_sym_COLON_EQ] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(81),
    [anon_sym_PLUS_PLUS] = ACTIONS(79),
    [anon_sym_DASH_DASH] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_DOLLAR] = ACTIONS(79),
    [aux_sym_integer_token1] = ACTIONS(81),
    [aux_sym_integer_token2] = ACTIONS(79),
    [sym_float] = ACTIONS(79),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [14] = {
    [sym_comment] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [sym_variable] = ACTIONS(83),
    [sym_atom] = ACTIONS(83),
    [anon_sym_SQUOTE] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(83),
    [anon_sym_LT_LT] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(83),
    [anon_sym_RBRACE] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(83),
    [anon_sym_RBRACK] = ACTIONS(83),
    [anon_sym_POUND_LBRACE] = ACTIONS(83),
    [anon_sym_POUND] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_EQ_GT] = ACTIONS(83),
    [anon_sym_COLON_EQ] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(85),
    [anon_sym_PLUS_PLUS] = ACTIONS(83),
    [anon_sym_DASH_DASH] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [anon_sym_DOLLAR] = ACTIONS(83),
    [aux_sym_integer_token1] = ACTIONS(85),
    [aux_sym_integer_token2] = ACTIONS(83),
    [sym_float] = ACTIONS(83),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [15] = {
    [sym_comment] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(87),
    [sym_variable] = ACTIONS(87),
    [sym_atom] = ACTIONS(87),
    [anon_sym_SQUOTE] = ACTIONS(87),
    [anon_sym_DQUOTE] = ACTIONS(87),
    [anon_sym_LT_LT] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(87),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(87),
    [anon_sym_POUND_LBRACE] = ACTIONS(87),
    [anon_sym_POUND] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PIPE] = ACTIONS(87),
    [anon_sym_EQ_GT] = ACTIONS(87),
    [anon_sym_COLON_EQ] = ACTIONS(87),
    [anon_sym_COLON] = ACTIONS(89),
    [anon_sym_PLUS_PLUS] = ACTIONS(87),
    [anon_sym_DASH_DASH] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_DOLLAR] = ACTIONS(87),
    [aux_sym_integer_token1] = ACTIONS(89),
    [aux_sym_integer_token2] = ACTIONS(87),
    [sym_float] = ACTIONS(87),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [16] = {
    [sym_comment] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(91),
    [anon_sym_RPAREN] = ACTIONS(91),
    [sym_variable] = ACTIONS(91),
    [sym_atom] = ACTIONS(91),
    [anon_sym_SQUOTE] = ACTIONS(91),
    [anon_sym_DQUOTE] = ACTIONS(91),
    [anon_sym_LT_LT] = ACTIONS(91),
    [anon_sym_GT_GT] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(91),
    [anon_sym_POUND_LBRACE] = ACTIONS(91),
    [anon_sym_POUND] = ACTIONS(93),
    [anon_sym_EQ] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(91),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_PIPE] = ACTIONS(91),
    [anon_sym_EQ_GT] = ACTIONS(91),
    [anon_sym_COLON_EQ] = ACTIONS(91),
    [anon_sym_COLON] = ACTIONS(93),
    [anon_sym_PLUS_PLUS] = ACTIONS(91),
    [anon_sym_DASH_DASH] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(91),
    [anon_sym_DOLLAR] = ACTIONS(91),
    [aux_sym_integer_token1] = ACTIONS(93),
    [aux_sym_integer_token2] = ACTIONS(91),
    [sym_float] = ACTIONS(91),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [17] = {
    [sym_comment] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(95),
    [sym_variable] = ACTIONS(95),
    [sym_atom] = ACTIONS(95),
    [anon_sym_SQUOTE] = ACTIONS(95),
    [anon_sym_DQUOTE] = ACTIONS(95),
    [anon_sym_LT_LT] = ACTIONS(95),
    [anon_sym_GT_GT] = ACTIONS(95),
    [anon_sym_LBRACE] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(95),
    [anon_sym_POUND_LBRACE] = ACTIONS(95),
    [anon_sym_POUND] = ACTIONS(97),
    [anon_sym_EQ] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(95),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_PIPE] = ACTIONS(95),
    [anon_sym_EQ_GT] = ACTIONS(95),
    [anon_sym_COLON_EQ] = ACTIONS(95),
    [anon_sym_COLON] = ACTIONS(97),
    [anon_sym_PLUS_PLUS] = ACTIONS(95),
    [anon_sym_DASH_DASH] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(95),
    [anon_sym_DOLLAR] = ACTIONS(95),
    [aux_sym_integer_token1] = ACTIONS(97),
    [aux_sym_integer_token2] = ACTIONS(95),
    [sym_float] = ACTIONS(95),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [18] = {
    [sym_comment] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(99),
    [sym_variable] = ACTIONS(99),
    [sym_atom] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(99),
    [anon_sym_DQUOTE] = ACTIONS(99),
    [anon_sym_LT_LT] = ACTIONS(99),
    [anon_sym_GT_GT] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_RBRACK] = ACTIONS(99),
    [anon_sym_POUND_LBRACE] = ACTIONS(99),
    [anon_sym_POUND] = ACTIONS(101),
    [anon_sym_EQ] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(101),
    [anon_sym_STAR] = ACTIONS(99),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_PIPE] = ACTIONS(99),
    [anon_sym_EQ_GT] = ACTIONS(99),
    [anon_sym_COLON_EQ] = ACTIONS(99),
    [anon_sym_COLON] = ACTIONS(101),
    [anon_sym_PLUS_PLUS] = ACTIONS(99),
    [anon_sym_DASH_DASH] = ACTIONS(99),
    [anon_sym_COMMA] = ACTIONS(99),
    [anon_sym_DOLLAR] = ACTIONS(99),
    [aux_sym_integer_token1] = ACTIONS(101),
    [aux_sym_integer_token2] = ACTIONS(99),
    [sym_float] = ACTIONS(99),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [19] = {
    [sym_comment] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(103),
    [sym_variable] = ACTIONS(103),
    [sym_atom] = ACTIONS(103),
    [anon_sym_SQUOTE] = ACTIONS(103),
    [anon_sym_DQUOTE] = ACTIONS(103),
    [anon_sym_LT_LT] = ACTIONS(103),
    [anon_sym_GT_GT] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_POUND_LBRACE] = ACTIONS(103),
    [anon_sym_POUND] = ACTIONS(105),
    [anon_sym_EQ] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(103),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_PIPE] = ACTIONS(103),
    [anon_sym_EQ_GT] = ACTIONS(103),
    [anon_sym_COLON_EQ] = ACTIONS(103),
    [anon_sym_COLON] = ACTIONS(105),
    [anon_sym_PLUS_PLUS] = ACTIONS(103),
    [anon_sym_DASH_DASH] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(103),
    [anon_sym_DOLLAR] = ACTIONS(103),
    [aux_sym_integer_token1] = ACTIONS(105),
    [aux_sym_integer_token2] = ACTIONS(103),
    [sym_float] = ACTIONS(103),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [20] = {
    [sym_comment] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_RPAREN] = ACTIONS(107),
    [sym_variable] = ACTIONS(107),
    [sym_atom] = ACTIONS(107),
    [anon_sym_SQUOTE] = ACTIONS(107),
    [anon_sym_DQUOTE] = ACTIONS(107),
    [anon_sym_LT_LT] = ACTIONS(107),
    [anon_sym_GT_GT] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(107),
    [anon_sym_RBRACK] = ACTIONS(107),
    [anon_sym_POUND_LBRACE] = ACTIONS(107),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(107),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_PIPE] = ACTIONS(107),
    [anon_sym_EQ_GT] = ACTIONS(107),
    [anon_sym_COLON_EQ] = ACTIONS(107),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_PLUS_PLUS] = ACTIONS(107),
    [anon_sym_DASH_DASH] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(107),
    [anon_sym_DOLLAR] = ACTIONS(107),
    [aux_sym_integer_token1] = ACTIONS(109),
    [aux_sym_integer_token2] = ACTIONS(107),
    [sym_float] = ACTIONS(107),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [21] = {
    [sym_comment] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(111),
    [anon_sym_RPAREN] = ACTIONS(111),
    [sym_variable] = ACTIONS(111),
    [sym_atom] = ACTIONS(111),
    [anon_sym_SQUOTE] = ACTIONS(111),
    [anon_sym_DQUOTE] = ACTIONS(111),
    [anon_sym_LT_LT] = ACTIONS(111),
    [anon_sym_GT_GT] = ACTIONS(111),
    [anon_sym_LBRACE] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(111),
    [anon_sym_POUND_LBRACE] = ACTIONS(111),
    [anon_sym_POUND] = ACTIONS(113),
    [anon_sym_EQ] = ACTIONS(113),
    [anon_sym_PLUS] = ACTIONS(113),
    [anon_sym_DASH] = ACTIONS(113),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_PIPE] = ACTIONS(111),
    [anon_sym_EQ_GT] = ACTIONS(111),
    [anon_sym_COLON_EQ] = ACTIONS(111),
    [anon_sym_COLON] = ACTIONS(113),
    [anon_sym_PLUS_PLUS] = ACTIONS(111),
    [anon_sym_DASH_DASH] = ACTIONS(111),
    [anon_sym_COMMA] = ACTIONS(111),
    [anon_sym_DOLLAR] = ACTIONS(111),
    [aux_sym_integer_token1] = ACTIONS(113),
    [aux_sym_integer_token2] = ACTIONS(111),
    [sym_float] = ACTIONS(111),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [22] = {
    [sym_comment] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(115),
    [anon_sym_RPAREN] = ACTIONS(115),
    [sym_variable] = ACTIONS(115),
    [sym_atom] = ACTIONS(115),
    [anon_sym_SQUOTE] = ACTIONS(115),
    [anon_sym_DQUOTE] = ACTIONS(115),
    [anon_sym_LT_LT] = ACTIONS(115),
    [anon_sym_GT_GT] = ACTIONS(115),
    [anon_sym_LBRACE] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(115),
    [anon_sym_RBRACK] = ACTIONS(115),
    [anon_sym_POUND_LBRACE] = ACTIONS(115),
    [anon_sym_POUND] = ACTIONS(117),
    [anon_sym_EQ] = ACTIONS(117),
    [anon_sym_PLUS] = ACTIONS(117),
    [anon_sym_DASH] = ACTIONS(117),
    [anon_sym_STAR] = ACTIONS(115),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_PIPE] = ACTIONS(115),
    [anon_sym_EQ_GT] = ACTIONS(115),
    [anon_sym_COLON_EQ] = ACTIONS(115),
    [anon_sym_COLON] = ACTIONS(117),
    [anon_sym_PLUS_PLUS] = ACTIONS(115),
    [anon_sym_DASH_DASH] = ACTIONS(115),
    [anon_sym_COMMA] = ACTIONS(115),
    [anon_sym_DOLLAR] = ACTIONS(115),
    [aux_sym_integer_token1] = ACTIONS(117),
    [aux_sym_integer_token2] = ACTIONS(115),
    [sym_float] = ACTIONS(115),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [23] = {
    [sym_comment] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_RPAREN] = ACTIONS(119),
    [sym_variable] = ACTIONS(119),
    [sym_atom] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(119),
    [anon_sym_LT_LT] = ACTIONS(119),
    [anon_sym_GT_GT] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(119),
    [anon_sym_RBRACK] = ACTIONS(119),
    [anon_sym_POUND_LBRACE] = ACTIONS(119),
    [anon_sym_POUND] = ACTIONS(121),
    [anon_sym_EQ] = ACTIONS(121),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [anon_sym_STAR] = ACTIONS(119),
    [anon_sym_SLASH] = ACTIONS(119),
    [anon_sym_PIPE] = ACTIONS(119),
    [anon_sym_EQ_GT] = ACTIONS(119),
    [anon_sym_COLON_EQ] = ACTIONS(119),
    [anon_sym_COLON] = ACTIONS(121),
    [anon_sym_PLUS_PLUS] = ACTIONS(119),
    [anon_sym_DASH_DASH] = ACTIONS(119),
    [anon_sym_COMMA] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(119),
    [aux_sym_integer_token1] = ACTIONS(121),
    [aux_sym_integer_token2] = ACTIONS(119),
    [sym_float] = ACTIONS(119),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [24] = {
    [sym_comment] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(123),
    [anon_sym_RPAREN] = ACTIONS(123),
    [sym_variable] = ACTIONS(123),
    [sym_atom] = ACTIONS(123),
    [anon_sym_SQUOTE] = ACTIONS(123),
    [anon_sym_DQUOTE] = ACTIONS(123),
    [anon_sym_LT_LT] = ACTIONS(123),
    [anon_sym_GT_GT] = ACTIONS(123),
    [anon_sym_LBRACE] = ACTIONS(123),
    [anon_sym_RBRACE] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(123),
    [anon_sym_RBRACK] = ACTIONS(123),
    [anon_sym_POUND_LBRACE] = ACTIONS(123),
    [anon_sym_POUND] = ACTIONS(125),
    [anon_sym_EQ] = ACTIONS(125),
    [anon_sym_PLUS] = ACTIONS(125),
    [anon_sym_DASH] = ACTIONS(125),
    [anon_sym_STAR] = ACTIONS(123),
    [anon_sym_SLASH] = ACTIONS(123),
    [anon_sym_PIPE] = ACTIONS(123),
    [anon_sym_EQ_GT] = ACTIONS(123),
    [anon_sym_COLON_EQ] = ACTIONS(123),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_PLUS_PLUS] = ACTIONS(123),
    [anon_sym_DASH_DASH] = ACTIONS(123),
    [anon_sym_COMMA] = ACTIONS(123),
    [anon_sym_DOLLAR] = ACTIONS(123),
    [aux_sym_integer_token1] = ACTIONS(125),
    [aux_sym_integer_token2] = ACTIONS(123),
    [sym_float] = ACTIONS(123),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [25] = {
    [sym_comment] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(127),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(127),
    [sym_variable] = ACTIONS(127),
    [sym_atom] = ACTIONS(127),
    [anon_sym_SQUOTE] = ACTIONS(127),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [anon_sym_LT_LT] = ACTIONS(127),
    [anon_sym_GT_GT] = ACTIONS(127),
    [anon_sym_LBRACE] = ACTIONS(127),
    [anon_sym_RBRACE] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(127),
    [anon_sym_RBRACK] = ACTIONS(127),
    [anon_sym_POUND_LBRACE] = ACTIONS(127),
    [anon_sym_POUND] = ACTIONS(129),
    [anon_sym_EQ] = ACTIONS(129),
    [anon_sym_PLUS] = ACTIONS(129),
    [anon_sym_DASH] = ACTIONS(129),
    [anon_sym_STAR] = ACTIONS(127),
    [anon_sym_SLASH] = ACTIONS(127),
    [anon_sym_PIPE] = ACTIONS(127),
    [anon_sym_EQ_GT] = ACTIONS(127),
    [anon_sym_COLON_EQ] = ACTIONS(127),
    [anon_sym_COLON] = ACTIONS(129),
    [anon_sym_PLUS_PLUS] = ACTIONS(127),
    [anon_sym_DASH_DASH] = ACTIONS(127),
    [anon_sym_COMMA] = ACTIONS(127),
    [anon_sym_DOLLAR] = ACTIONS(127),
    [aux_sym_integer_token1] = ACTIONS(129),
    [aux_sym_integer_token2] = ACTIONS(127),
    [sym_float] = ACTIONS(127),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [26] = {
    [sym_comment] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(131),
    [anon_sym_LPAREN] = ACTIONS(131),
    [anon_sym_RPAREN] = ACTIONS(131),
    [sym_variable] = ACTIONS(131),
    [sym_atom] = ACTIONS(131),
    [anon_sym_SQUOTE] = ACTIONS(131),
    [anon_sym_DQUOTE] = ACTIONS(131),
    [anon_sym_LT_LT] = ACTIONS(131),
    [anon_sym_GT_GT] = ACTIONS(131),
    [anon_sym_LBRACE] = ACTIONS(133),
    [anon_sym_RBRACE] = ACTIONS(131),
    [anon_sym_LBRACK] = ACTIONS(131),
    [anon_sym_RBRACK] = ACTIONS(131),
    [anon_sym_POUND_LBRACE] = ACTIONS(131),
    [anon_sym_POUND] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(135),
    [anon_sym_DASH] = ACTIONS(135),
    [anon_sym_STAR] = ACTIONS(131),
    [anon_sym_SLASH] = ACTIONS(131),
    [anon_sym_PIPE] = ACTIONS(131),
    [anon_sym_EQ_GT] = ACTIONS(131),
    [anon_sym_COLON_EQ] = ACTIONS(131),
    [anon_sym_COLON] = ACTIONS(135),
    [anon_sym_PLUS_PLUS] = ACTIONS(131),
    [anon_sym_DASH_DASH] = ACTIONS(131),
    [anon_sym_COMMA] = ACTIONS(131),
    [anon_sym_DOLLAR] = ACTIONS(131),
    [aux_sym_integer_token1] = ACTIONS(135),
    [aux_sym_integer_token2] = ACTIONS(131),
    [sym_float] = ACTIONS(131),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [27] = {
    [sym_comment] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(137),
    [anon_sym_RPAREN] = ACTIONS(137),
    [sym_variable] = ACTIONS(137),
    [sym_atom] = ACTIONS(137),
    [anon_sym_SQUOTE] = ACTIONS(137),
    [anon_sym_DQUOTE] = ACTIONS(137),
    [anon_sym_LT_LT] = ACTIONS(137),
    [anon_sym_GT_GT] = ACTIONS(137),
    [anon_sym_LBRACE] = ACTIONS(137),
    [anon_sym_RBRACE] = ACTIONS(137),
    [anon_sym_LBRACK] = ACTIONS(137),
    [anon_sym_RBRACK] = ACTIONS(137),
    [anon_sym_POUND_LBRACE] = ACTIONS(137),
    [anon_sym_POUND] = ACTIONS(139),
    [anon_sym_EQ] = ACTIONS(139),
    [anon_sym_PLUS] = ACTIONS(139),
    [anon_sym_DASH] = ACTIONS(139),
    [anon_sym_STAR] = ACTIONS(137),
    [anon_sym_SLASH] = ACTIONS(137),
    [anon_sym_PIPE] = ACTIONS(137),
    [anon_sym_EQ_GT] = ACTIONS(137),
    [anon_sym_COLON_EQ] = ACTIONS(137),
    [anon_sym_COLON] = ACTIONS(139),
    [anon_sym_PLUS_PLUS] = ACTIONS(137),
    [anon_sym_DASH_DASH] = ACTIONS(137),
    [anon_sym_COMMA] = ACTIONS(137),
    [anon_sym_DOLLAR] = ACTIONS(137),
    [aux_sym_integer_token1] = ACTIONS(139),
    [aux_sym_integer_token2] = ACTIONS(137),
    [sym_float] = ACTIONS(137),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [28] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(65),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(28),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [29] = {
    [sym__expression] = STATE(37),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(29),
    [aux_sym_source_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(145),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [30] = {
    [sym__expression] = STATE(37),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(30),
    [aux_sym_source_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(149),
    [sym_variable] = ACTIONS(152),
    [sym_atom] = ACTIONS(155),
    [anon_sym_SQUOTE] = ACTIONS(158),
    [anon_sym_DQUOTE] = ACTIONS(161),
    [anon_sym_LT_LT] = ACTIONS(164),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(170),
    [anon_sym_POUND_LBRACE] = ACTIONS(173),
    [anon_sym_POUND] = ACTIONS(176),
    [anon_sym_DOLLAR] = ACTIONS(179),
    [aux_sym_integer_token1] = ACTIONS(182),
    [aux_sym_integer_token2] = ACTIONS(185),
    [sym_float] = ACTIONS(155),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [31] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(62),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(31),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(188),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [32] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(61),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(32),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [33] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(68),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(33),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(192),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [34] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(67),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(34),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(194),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [35] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(66),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(35),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_GT_GT] = ACTIONS(196),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [36] = {
    [sym__expression] = STATE(44),
    [sym_quoted_atom] = STATE(18),
    [sym_string] = STATE(18),
    [sym_bitstring] = STATE(18),
    [sym_tuple] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_record] = STATE(18),
    [sym_binary_operator] = STATE(18),
    [sym__items] = STATE(64),
    [sym_character] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_comment] = STATE(36),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_variable] = ACTIONS(141),
    [sym_atom] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(198),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND_LBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(27),
    [aux_sym_integer_token1] = ACTIONS(29),
    [aux_sym_integer_token2] = ACTIONS(31),
    [sym_float] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [37] = {
    [sym_comment] = STATE(37),
    [ts_builtin_sym_end] = ACTIONS(200),
    [anon_sym_LPAREN] = ACTIONS(200),
    [sym_variable] = ACTIONS(200),
    [sym_atom] = ACTIONS(200),
    [anon_sym_SQUOTE] = ACTIONS(200),
    [anon_sym_DQUOTE] = ACTIONS(200),
    [anon_sym_LT_LT] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_POUND_LBRACE] = ACTIONS(200),
    [anon_sym_POUND] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(204),
    [anon_sym_PLUS] = ACTIONS(204),
    [anon_sym_DASH] = ACTIONS(204),
    [anon_sym_STAR] = ACTIONS(206),
    [anon_sym_SLASH] = ACTIONS(206),
    [anon_sym_PIPE] = ACTIONS(206),
    [anon_sym_EQ_GT] = ACTIONS(206),
    [anon_sym_COLON_EQ] = ACTIONS(206),
    [anon_sym_COLON] = ACTIONS(204),
    [anon_sym_PLUS_PLUS] = ACTIONS(206),
    [anon_sym_DASH_DASH] = ACTIONS(206),
    [anon_sym_DOLLAR] = ACTIONS(200),
    [aux_sym_integer_token1] = ACTIONS(202),
    [aux_sym_integer_token2] = ACTIONS(200),
    [sym_float] = ACTIONS(200),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
  [38] = {
    [sym_comment] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(99),
    [sym_variable] = ACTIONS(99),
    [sym_atom] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(99),
    [anon_sym_DQUOTE] = ACTIONS(99),
    [anon_sym_LT_LT] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_POUND_LBRACE] = ACTIONS(208),
    [anon_sym_POUND] = ACTIONS(211),
    [anon_sym_EQ] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(101),
    [anon_sym_STAR] = ACTIONS(99),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_PIPE] = ACTIONS(99),
    [anon_sym_EQ_GT] = ACTIONS(99),
    [anon_sym_COLON_EQ] = ACTIONS(99),
    [anon_sym_COLON] = ACTIONS(101),
    [anon_sym_PLUS_PLUS] = ACTIONS(99),
    [anon_sym_DASH_DASH] = ACTIONS(99),
    [anon_sym_DOLLAR] = ACTIONS(99),
    [aux_sym_integer_token1] = ACTIONS(101),
    [aux_sym_integer_token2] = ACTIONS(99),
    [sym_float] = ACTIONS(99),
    [aux_sym_comment_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LT_LT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 1,
      aux_sym_integer_token1,
    ACTIONS(31), 1,
      aux_sym_integer_token2,
    ACTIONS(141), 1,
      sym_variable,
    STATE(13), 1,
      sym__expression,
    STATE(39), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_atom,
      sym_float,
    STATE(18), 10,
      sym_quoted_atom,
      sym_string,
      sym_bitstring,
      sym_tuple,
      sym_list,
      sym_map,
      sym_record,
      sym_binary_operator,
      sym_character,
      sym_integer,
  [62] = 17,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_variable,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LT_LT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 1,
      aux_sym_integer_token1,
    ACTIONS(31), 1,
      aux_sym_integer_token2,
    STATE(13), 1,
      sym__expression,
    STATE(40), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_atom,
      sym_float,
    STATE(18), 10,
      sym_quoted_atom,
      sym_string,
      sym_bitstring,
      sym_tuple,
      sym_list,
      sym_map,
      sym_record,
      sym_binary_operator,
      sym_character,
      sym_integer,
  [124] = 17,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LT_LT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 1,
      aux_sym_integer_token1,
    ACTIONS(31), 1,
      aux_sym_integer_token2,
    ACTIONS(214), 1,
      sym_variable,
    STATE(41), 1,
      sym_comment,
    STATE(48), 1,
      sym__expression,
    ACTIONS(216), 2,
      sym_atom,
      sym_float,
    STATE(47), 10,
      sym_quoted_atom,
      sym_string,
      sym_bitstring,
      sym_tuple,
      sym_list,
      sym_map,
      sym_record,
      sym_binary_operator,
      sym_character,
      sym_integer,
  [186] = 17,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LT_LT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 1,
      aux_sym_integer_token1,
    ACTIONS(31), 1,
      aux_sym_integer_token2,
    ACTIONS(141), 1,
      sym_variable,
    STATE(42), 1,
      sym_comment,
    STATE(45), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_atom,
      sym_float,
    STATE(18), 10,
      sym_quoted_atom,
      sym_string,
      sym_bitstring,
      sym_tuple,
      sym_list,
      sym_map,
      sym_record,
      sym_binary_operator,
      sym_character,
      sym_integer,
  [248] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(218), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(220), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_comment,
    ACTIONS(101), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(99), 12,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_COMMA,
  [281] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym__items_repeat1,
    ACTIONS(222), 3,
      anon_sym_GT_GT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    ACTIONS(224), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(226), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [314] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(45), 1,
      sym_comment,
    ACTIONS(224), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(230), 4,
      anon_sym_GT_GT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(226), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [342] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(218), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(220), 1,
      anon_sym_POUND,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_comment,
    ACTIONS(101), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(99), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [373] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      sym_comment,
    ACTIONS(101), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(99), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [398] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(48), 1,
      sym_comment,
    ACTIONS(224), 4,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COLON,
    ACTIONS(226), 7,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_EQ_GT,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [420] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(234), 1,
      sym_variable,
    ACTIONS(236), 1,
      sym_atom,
    STATE(7), 1,
      sym__atom,
    STATE(9), 1,
      sym__identifier,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(49), 1,
      sym_comment,
  [445] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(234), 1,
      sym_variable,
    ACTIONS(236), 1,
      sym_atom,
    STATE(7), 1,
      sym__atom,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(26), 1,
      sym__identifier,
    STATE(50), 1,
      sym_comment,
  [470] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(51), 2,
      sym_comment,
      aux_sym__items_repeat1,
    ACTIONS(230), 3,
      anon_sym_GT_GT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [486] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym__items_repeat1,
    STATE(52), 1,
      sym_comment,
    ACTIONS(241), 3,
      anon_sym_GT_GT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [504] = 5,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    STATE(53), 1,
      sym_comment,
    STATE(54), 1,
      aux_sym_string_repeat1,
    ACTIONS(245), 2,
      sym_escape_sequence,
      sym_quoted_content,
  [521] = 4,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    ACTIONS(249), 1,
      anon_sym_DQUOTE,
    ACTIONS(251), 2,
      sym_escape_sequence,
      sym_quoted_content,
    STATE(54), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [536] = 5,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      aux_sym_string_repeat1,
    STATE(55), 1,
      sym_comment,
    ACTIONS(245), 2,
      sym_escape_sequence,
      sym_quoted_content,
  [553] = 3,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    STATE(56), 1,
      sym_comment,
    ACTIONS(256), 3,
      anon_sym_DQUOTE,
      sym_escape_sequence,
      sym_quoted_content,
  [565] = 3,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    STATE(57), 1,
      sym_comment,
    ACTIONS(258), 2,
      sym_escape_sequence,
      aux_sym_character_token1,
  [576] = 3,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    ACTIONS(260), 1,
      aux_sym_comment_token2,
    STATE(58), 1,
      sym_comment,
  [586] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
    STATE(59), 1,
      sym_comment,
  [596] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(264), 1,
      anon_sym_SQUOTE,
    STATE(60), 1,
      sym_comment,
  [606] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_comment,
  [616] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      sym_comment,
  [626] = 3,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    ACTIONS(270), 1,
      sym_quoted_content,
    STATE(63), 1,
      sym_comment,
  [636] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_comment,
  [646] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_comment,
  [656] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(276), 1,
      anon_sym_GT_GT,
    STATE(66), 1,
      sym_comment,
  [666] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_comment,
  [676] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(280), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      sym_comment,
  [686] = 1,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(39)] = 0,
  [SMALL_STATE(40)] = 62,
  [SMALL_STATE(41)] = 124,
  [SMALL_STATE(42)] = 186,
  [SMALL_STATE(43)] = 248,
  [SMALL_STATE(44)] = 281,
  [SMALL_STATE(45)] = 314,
  [SMALL_STATE(46)] = 342,
  [SMALL_STATE(47)] = 373,
  [SMALL_STATE(48)] = 398,
  [SMALL_STATE(49)] = 420,
  [SMALL_STATE(50)] = 445,
  [SMALL_STATE(51)] = 470,
  [SMALL_STATE(52)] = 486,
  [SMALL_STATE(53)] = 504,
  [SMALL_STATE(54)] = 521,
  [SMALL_STATE(55)] = 536,
  [SMALL_STATE(56)] = 553,
  [SMALL_STATE(57)] = 565,
  [SMALL_STATE(58)] = 576,
  [SMALL_STATE(59)] = 586,
  [SMALL_STATE(60)] = 596,
  [SMALL_STATE(61)] = 606,
  [SMALL_STATE(62)] = 616,
  [SMALL_STATE(63)] = 626,
  [SMALL_STATE(64)] = 636,
  [SMALL_STATE(65)] = 646,
  [SMALL_STATE(66)] = 656,
  [SMALL_STATE(67)] = 666,
  [SMALL_STATE(68)] = 676,
  [SMALL_STATE(69)] = 686,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, .production_id = 4),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 5, .production_id = 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, .production_id = 6),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, .production_id = 6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, .production_id = 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 4, .production_id = 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifier, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifier, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, .production_id = 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, .production_id = 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, .production_id = 8),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 4, .production_id = 8),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3, .production_id = 7),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3, .production_id = 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 6, .production_id = 10),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 6, .production_id = 10),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitstring, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitstring, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitstring, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitstring, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 5),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, .production_id = 5),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, .production_id = 5),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, .production_id = 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, .production_id = 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, .production_id = 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, .production_id = 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 3, .production_id = 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, .production_id = 9),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 5, .production_id = 9),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(41),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(38),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(18),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(63),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(55),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(35),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(34),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(33),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(32),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(49),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(57),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(14),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(14),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__expression, 1), SHIFT(28),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__expression, 1), SHIFT(50),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items, 1),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__items_repeat1, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__items_repeat1, 2), SHIFT_REPEAT(42),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items, 2),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [251] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(56),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [262] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, .production_id = 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_erlang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
